common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 320000
  min_sample_size: 12000
  normalize: true

dataset:
  batch_size: 4
  num_workers: 6
  max_tokens: 800000
  valid_subset: dev
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 128
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 0]

optimization:
  max_update: 1000000
  lr: [0.0002]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01


lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 25000

model:
#  _name: wav2vec2
  _name: conformer_based_wav2vec2
  is_mel_spectrograms: true
  quantize_targets: true
  extractor_mode: layer_norm
  layer_norm_first: true
  final_dim: 768
  latent_temp: [2.0,0.1,0.999995]
  encoder_layerdrop: 0.00
  dropout_input: 0.0
  dropout_features: 0.0
  dropout: 0.0
  attention_dropout: 0.0
  conv_bias: true
  num_negatives: 100
  logit_temp: 0.1
  max_source_positions: 3000
  mask_prob: 0.65
  mask_selection: static
  mask_other: 0
  no_mask_overlap: false
  mask_min_space: 1
  mask_channel_length: 10
  mask_channel_prob: 0.0
  mask_channel_before: false
  mask_channel_selection: static
  mask_channel_other: 0
  no_mask_channel_overlap: false
  mask_channel_min_space: 1
  mask_length: 10
  conv_pos: 128
  conv_pos_groups: 16
  codebook_negatives: 0
  latent_dim: 0
  latent_vars: 320
  latent_groups: 2
  quantizer_depth: 1
  quantizer_factor: 3
  target_glu: false
  same_quantizer: false
  negatives_from_everywhere: false
  cross_sample_negatives: 0
  activation_dropout: 0
  encoder_layers: 8
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 8
  input_feat_per_channel: 1
  feature_grad_mult: 1.0
  quantize_input: false

  decoder_normalize_before: True
  encoder_normalize_before: True
  conv_kernel_sizes: 5,5
  conv_channels: 512
  activation_fn: swish
  conv_feature_layers: '[(1024, 10, 5)] + [(1024, 3, 2)] * 4 + [(1024,2,2)] + [(1024,2,2)]'
  macaron_style: True
  use_cnn_module: True
  cnn_module_kernel: 31
  quant_noise_pq: 0
  encoder_attention_type: selfattn
